In [3]:
mat=tf.constant([[3,4,5,8],[4,5,6,7],[1,1,1,1]])
print(mat)
matmax=tf.math.reduce_max(mat,axis=1)
print(matmax)

tf.Tensor(
[[3 4 5 8]
 [4 5 6 7]
 [1 1 1 1]], shape=(3, 4), dtype=int32)
tf.Tensor([8 7 1], shape=(3,), dtype=int32)


In [1]:
import tensorflow as tf
a=tf.constant([[3,4,5,8],[4,5,6,7],[1,1,1,1]])
b=tf.constant([[1,1,1,1],[7,2,2,2],[2,2,2,2]])
c=tf.add(a,b)
print(c)

tf.Tensor(
[[ 4  5  6  9]
 [11  7  8  9]
 [ 3  3  3  3]], shape=(3, 4), dtype=int32)


In [2]:
list=[[1,2,3],[4,5,6],[1,1,1]]
a=tf.constant([[2,3,4],[1,3,4],[6,3,1]])
c=tf.add(list,a)
print(c)


tf.Tensor(
[[ 3  5  7]
 [ 5  8 10]
 [ 7  4  2]], shape=(3, 3), dtype=int32)
